/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_XD_inverterterminal_serial_jni_SciClass */

#ifndef _Included_com_XD_inverterterminal_serial_jni_SciClass
#define _Included_com_XD_inverterterminal_serial_jni_SciClass
#ifdef __cplusplus
extern "C" {
#endif
#undef com_XD_inverterterminal_serial_jni_SciClass_OLD_CHECK
#define com_XD_inverterterminal_serial_jni_SciClass_OLD_CHECK 1L
#undef com_XD_inverterterminal_serial_jni_SciClass_NONE_CHECK
#define com_XD_inverterterminal_serial_jni_SciClass_NONE_CHECK 0L
#undef com_XD_inverterterminal_serial_jni_SciClass_EVEN_CHECK
#define com_XD_inverterterminal_serial_jni_SciClass_EVEN_CHECK 2L
/*
 * Class:     com_XD_inverterterminal_serial_jni_SciClass
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_XD_inverterterminal_serial_1jni_SciClass_open
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_XD_inverterterminal_serial_jni_SciClass
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_XD_inverterterminal_serial_1jni_SciClass_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
